### ISSUE TITLE
Trigger for wholesale settlement processes 

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#166]
Should be separate databricks job attached to existing cluster
Create azure http trigger function
Paramter list:
From date
To date
Process variant (Correction settlement only)
Process type
Etc.

**Comment by MadsBloendAndersen** [comment]
Hey @mknic. Whenever a wholesale settlement process is triggered (D05, D32), both BRS-023 and BRS-027 calculations should be triggered. is this included in this issue?

**Comment by ZavezX** [comment]
@MadsBloendAndersen this issue only revolves around the function of triggering the wholesale specific calculations. Because aggregation and wholesale results are unrelated, then they can be triggered separately (after each other).
