### ISSUE TITLE
Calculation based on hourly tariff for flex metering points

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#167]
Calculate:
Energy quantity per hourly tariff (kWh)
Price per tariff (DKK/kWh/day) 
Amounts (DKK) (Energy Quantity * price)

Filter on the following
- Daily tariffs+ChargeOwner per flex MP per energy supplier per grid area

Energy quantity and prices is measured in hourly resolution. Each price per hour is multiplied with the respective hourly energy quantity. 

IF the MP is PT15M, 
THEN each 15 min is summed up into one hour, which is then, multiplies with the hourly price.

*Accept Criterias*
1. Input and output data is present in the excel validation sheet
2. Output of the calculation has been verified
3. "What should the result look like?"
4. Unit test on prices should reflect precision 8 decimals
5. Unit test cover the expected rounding rules (see page 287 in RSM guide)

**Comment by MadsBloendAndersen** [comment]
@ZavezX Result for this issue are documented in the excel sheet. Both Energy Quantity, prices and amounts.
