### ISSUE TITLE
Calculation based on subscriptions per flex consumption

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#169]
Calculate:
Quantity per subscription (number of the same subscription connected to one metering point)

e.g 
MP1 has 2 subscription

Sub1
- Quantity = 5 
Sub2 
- Quantity = 1

Price per subscription (DKK/kWh/month) 
Amounts (DKK) (Quantity * Price)

Filter on the following
- subscriptions(+ChargeOwner) per flex MP per energy supplier per grid area 

The price of a subscription is monthly and needs to be distributed across all days in the calculated period. 

IF the calculating period is crossing over the 1st of a month,
THEN you will get two different days values, one for each month (unless there are equal number of days in the two months, including in the period)

e.g
Sub price = 100 DKK/month
January = 31 days
february = 28 days  

calculation period = 15 jan to 15 feb

Daily values for subscription
Jan = 100/31
Feb = 100/28

*Accept Criterias*
1. Input and output data is present in the excel validation sheet
2. Output of the calculation has been verified
3. The following parameters must be part of the results
- ChargeCode (ChargeID)
- ChargeOwner
- EnergySupplier
- GridArea
- subscription quantity (number of subscriptions) 
- prices per subscription per day
- daily amounts (subscription quantity * subscription price per day)
- Metering Point Type
- Settlement method
- ChargeType

4. Unit test on prices should reflect precision 8 decimals
5. Unit test cover the expected rounding rules (see rules in RSM-guide p. 287)

**Comment by MadsBloendAndersen** [comment]
Connected to issue #221
