### ISSUE TITLE
Calculation based on fees per flex consumption metering points

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#170]
Calculate:
Quantity per fee (kWh) (number of the same fee connected to one metering point)
Price per fee(DKK/kWh/day) 
Amounts (DKK) (Quantity )

Filter on the following
- fees+ChargeOwner per flex MP per energy supplier per grid area 

Fees are calculated on days where fees has been linked on the metering point. One time payments

e. g
A grid operator has connected your physical meter at your house on date X, at a cost Y.
This Y (fee price) will then be present on date X

*Accept Criterias*
1. Input and output data is present in the excel validation sheet
2. Output of the calculation has been verified
3. The following parameters must be part of the results
- ChargeCode (ChargeID)
- ChargeOwner
- EnergySupplier
- GridArea
- fee quantity (number of fees) 
- prices per fees per day
- amounts (fee quantity per day * fee price per day)
- Metering Point Type
- Settlement method
- ChargeType

**Comment by mknic** [comment]
1) Remove invalid time-series rows from input data eg. for metering point 578710000000000110 where it has an energy quantity within a time window where there's no energy supplier attached to the metering point.

2) Fix macro for generating charge prices. Currently, it has duplicates which should not be possible.

**Comment by kristianschneider** [comment]
If there exists a charge link for a given metering point on given day, the fee should be added to the result
