### ISSUE TITLE
[Spike] Understand content in RSM-019 in CIM XML format 

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#171]
We need to understand the content of RSM-014 and RSM-019 in CIM XML format. 

The following example message can be found in DH3ART teams channel (see the comment below from @MadsBloendAndersen)

**Comment by MadsBloendAndersen** [comment]
The following example messages can be found here in the team channel:

DH3ART -> Generel -> Files:
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/a9718553-e581-444a-bc96-b479c4f87e2f)


Here we can both find example on RSM-014 and RSM-019
