### ISSUE TITLE
Store wholesale settlement results in blob

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#172]
**Description**
Store results of the wholesale settlement for both tariffs, subscriptions and fees. 

Quantity: Can either be hourly EnergyQuantity, or number of subscriptions or fees 
Prices on all charges to a given time 
and amounts (Quantity * price) to a given time

Path to result blob must be in this format: Results/{JobID}/{FileName}

**Acceptance criteria**
1. Results from BRS-027 are store with the results from BRS-023

**Comment by mknic** [comment]
The following branch capture the initial work on storing results for wholesale:
https://github.com/Energinet-DataHub/geh-aggregations/tree/feature/172-store-wholesale-settlement-results

We tend to use the same approach and have modified the current method to store results to be able to handle both aggregation and wholesale results. 

The following lines of code need to be tried for both aggregation and wholesale results to make sure the method fits both purposes:
https://github.com/Energinet-DataHub/geh-aggregations/blob/feature/172-store-wholesale-settlement-results/source/databricks/geh_stream/aggregation_utils/services/aggregation_postprocessor.py#L33-L35
