### ISSUE TITLE
Store basis data for wholesale settlement job

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#174]
**Description**
We need to store basis data for a wholesale settlement process (Both D05 and D32_D01/D02/D03). Datahub needs this data for market actor to request them, and to handle any disputes with market actors. 

We need to rewrite the way we store basis data for aggregation process so that we store each dataframe individually before joining data from different sources. 
We will use the same approach as with storing results from calculations.

**Acceptance criteria**
1. Store dataframes individually before joining data
2. Paths to dataframes should have the following format: delta/basis-data/{jobId}/{filename}
3. Method to store dataframes should be moved to shared and should be used by aggregation and wholesale
4. Rename "result-id" to "job-id" from "coordinator" down to "trigger-base-arguments"

**Comment by mknic** [comment]
Proposed solutions:

1) Save raw dataframes from each source eg. Market Roles, Time series, Charges etc.
- We get full flexibility by storing dataframes for each source before joining data
- Filter on period and grid areas

2) Save joined dataframe before aggregation/wholesale jib is executed
- We can't create and store a complete dataframe before a wholesale job is executed
- Works for aggregation job

**Comment by mknic** [comment]
Together with @MadsBloendAndersen we found out that the the current way of storing basis data are problematic. The aggregatoin job and the wholesale job are two different jobs in databricks. In the beginnig of each job we store basis data but as the two jobs are not executed at the exact same time (only when running wholesale process which triggers both jobs) the basis data could potentially differ. This is not acceptable and a new issue to handle this has been created #268

Should we close this @MadsBloendAndersen knowing that the issue stated above would be handled in #268.
