### ISSUE TITLE
Setup eventhub time series connection string in IaC

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/geh-aggregations#184]
We need to know the key names provided by Volt

AC1: Values from keyvault are set in coordinator application settings
AC2: Lasse har været med på opgaven

**Comment by mknic** [comment]
@MadsBloendAndersen @KPeen this issue is no longer applicable since scope has changed and it's decided not to use eventhub as integration point between aggregation domain and time series domain.
