### ISSUE TITLE
Duplicates in validation data

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#210]
Hour 00:00:00 is duplicated in validation data on some metering points, for example metering point ID: 578710000000000105

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/2cbbab97-03a0-4d8d-a580-e7d0c155f03c)

**Comment by MadsBloendAndersen** [comment]
@kristianschneider as i was going through in the validation data i came across this bug, that probably needs to be fixed before we can do any validations on BRS-023.

**Comment by ZavezX** [comment]
Issue with time series generation resolved in: https://teams.microsoft.com/l/file/9B76E782-829E-476D-B225-EBA330FF92A2?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&fileType=xlsm&objectUrl=https%3A%2F%2Fenerginet.sharepoint.com%2Fsites%2FJoules%2FDelte%20dokumenter%2FGeneral%2FTest%20data%2FExcel%20sheet%20(BRS-023%2BBRS-027)v15%20(With%20results%20for%20BRS-023).xlsm&baseUrl=https%3A%2F%2Fenerginet.sharepoint.com%2Fsites%2FJoules&serviceName=teams&threadId=19:9be4db802bd24ed99af96f025a839eb2@thread.tacv2&groupId=e986ad70-5310-4581-bc33-eed0503bdfde
