### ISSUE TITLE
[Enabler] Examine Cosmos DB scaling on container level in context of Databricks usage

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#214]
Currently, we experience issues when the generator handles multiple CSV's from our test data blob and tries to insert data into our cosmos (master-data) containers. 

We need to investigate how to scale the individual containers to fit our needs and create a task to handle this in our terraform IaC code for creating the cosmos DB.

**Acceptcriterias**
1. Determine if COSMOS is the right way to go 
2. Understand and document the scaling strategy for our cosmos DB containers
3. Create an issue to implement the findings from 1.

**Comment by johevemi** [comment]
It is not possible to listen to a service bus from a structured streaming job in databricks, there for current conclusion is to stick the implementation using cosmos db to hold data coming from service bus. It is possible only with delta lake tables and event hubs in azure https://docs.databricks.com/spark/latest/structured-streaming/data-sources.html

**Comment by johevemi** [comment]
New task created regarding cosmos db scaling and performance #227
