### ISSUE TITLE
[Aggregation Domain] Define technical improvements

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#259]
In the coming IP sprint, we are about to discuss the technical debt. 
This issue should be used to track all the bullets we might have within the aggregation domain. 

List of issues we have in terms of technical depth:
- Add type to all parameters in python functions
- Remove load of data in [aggregation_initializer](https://github.com/Energinet-DataHub/geh-aggregations/blob/main/source/databricks/geh_stream/aggregation_utils/aggregators/aggregation_initializer.py) 
and use methods in [data_loader](https://github.com/Energinet-DataHub/geh-aggregations/blob/main/source/databricks/geh_stream/shared/data_loader.py)
- Flake8 doesn't work with python interpreter 3.8.10 --> we need to make sure the default interpreter is set to a specific version aligned with the python version we are using
- Our wheel file is still named: `geh_stream`. Should be renamed.
- Revisit the Coordinator and create issues to handle splitting up the coordinator into single responsible pieces. We should introduce the MediatR framework and introduce command/query pattern. The metering point domain is a good repository to take a look at for inspiration.

**Comment by MadsBloendAndersen** [comment]
@mknic will separate the bullet points into different issues

**Comment by MadsBloendAndersen** [comment]
@mknic har du oprettet issues på disse punkter?
