### ISSUE TITLE
Prepare demo of suggested tool for the SME's to test aggregations

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#261]
### Description
As a subject matter expert
I want to be able to test the calculation engine, for both BRS-023 and BRS-027
so that i can verify the results

### Acceptance criteria
1. Document the suggestion of how SME's can test aggregations

https://energinet.sharepoint.com/sites/Joules/Delte%20dokumenter/General/sme%20tool.drawio

**Comment by kristianschneider** [comment]
Drawing of how the test data is created, the entities involved, and the process.
Drawing is part of the Sprint demo prep
