### ISSUE TITLE
Snapshot between brs-023 and brs-027 must be coordinated 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#268]
**Description**
Split out the logic to fetch data from master data sources (cosmos) and time series (delta lake) and store the raw dataframes. 

We need to create a separate databricks job to be responsible for storing basis data. 

We should use `process type` as parameter to determine if it's basis data for aggregation process or wholesale process.

Aggregation process should store the following: `metering points`, `time series`, `market roles`, `grid loss and system correction`, `energy supplier balance responsible relationship`.

Wholesale process should store the following:`metering points`, `time series`, `market roles`, `charges`, `charge links`, `charge prices`.

**Accept criteria**
1) Databricks job to fetch and store data is triggered as part of a process (both aggregation and wholesale)
2) Basis data are stored in delta lake
3) What about the relation between aggregation job id, wholesale job id, and basis data?

**Note** 
Investigate if we are able to share data fetched and stored in this databriks job between aggregation job and wholesale job, or if we need to read data from delta tables in aggregation and wholesale jobs.

**Comment by mknic** [comment]
Share data between multiple databricks jobs: https://medium.com/@kar9475/data-sharing-between-multiple-spark-jobs-in-databricks-308687c99897

**Comment by kristianschneider** [comment]
![image.png](https://images.zenhubusercontent.com/60dae136fad0561c9902148c/1f1a57e0-4041-4aa6-9ee4-4274208d098b)

**Comment by ZavezX** [comment]
- Database must be changed to correspond to image below:
![image.png](https://images.zenhubusercontent.com/60dae1a8503a837b772b93a5/6df5e8ed-cb54-4ac2-a2dc-22c3b1a1deaf)

- When data preparation job is created, the snapshot must be inserted into the database.
- When other jobs are created they need a reference to a snapshot.
