### ISSUE TITLE
Upgrade strategy for Python, Databricks, Spark etc.

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#300]
Description
We need to implement a strategy on how and when to upgrade the following:

Databricks
Spark
Python
Python packages (Dependabot)
???
We need an upgrade strategy for production and development.

As we are using docker for local development when it comes to spark development we have seen issues where versions of spark get deprecated and are no longer available for download
That means our local development environment often will use a different spark version than we use in our hosted databricks environment. We are currently running on Databricks 7.3 LTS which uses spark 3.0.1 but uses spark 3.0.3 locally.
Spark versions available on here are 3.0.3 and up which means we can't replicate our hosted environment locally if we continue to download spark version directly when the docker container is build without cache.

Accept Criteria
1. Agree and document strategy for Databricks upgrade (hereby spark upgrade as well)
2. Agree and document strategy for Python and python packages upgrade
3. Agree and document how to make sure the Dockerfile follows the upgrade strategy (if we want to?)

**Comment by mknic** [comment]
**Description**
We need to implement a strategy on how and when to upgrade the following:
- Databricks
- Spark
- Python
- Python packages
- ??

We need an upgrade strategy for production and development.

As we are using docker for local development when it comes to spark development we have seen issues where versions of spark get deprecated and are no longer available for [download](https://dlcdn.apache.org/spark/)
That means our local development environment often will use a different spark version than we use in our hosted databricks environment. We are currently running on Databricks 7.3 LTS which uses spark 3.0.1 but uses spark 3.0.3 locally.
Spark versions available on [here](https://dlcdn.apache.org/spark/) are 3.0.3 and up which means we can't replicate our hosted environment locally if we continue to download spark version directly when the docker container is build without cache. 

**Accept Criteria**
1. Agree and document strategy for Databricks upgrade (hereby spark upgrade as well)
2. Agree and document strategy for Python and python packages upgrade
3. Agree and document how to make sure the Dockerfile follows the upgrade strategy (if we want to?)

**Comment by BjarkeMeier** [comment]
I believe we need to agree on a strategy with the architects similar to our .NET upgrade strategies. I'd like to be involved in this story.

**Comment by MadsBloendAndersen** [comment]
@Sondergaard We flagged this issue as a risk last PI, that we don't have a strategy for databricks/python upgrades. Are you and @MartinFHansen able to drive this further?
