### ISSUE TITLE
Force databricks cluster to stop on deployment

### ISSUE THREAD

**Issue by ZavezX** [Energinet-DataHub/geh-aggregations#311]
When we run deployment to databricks we should restart cluster after deployment. 

Maybe this can be done from terraform.

We want to do this because if the cluster is running, it does not pick up the changes before it is restarted.

ac 1) When pyspark code is deployed on a running cluster, the cluster is restarted

**Comment by kristianschneider** [comment]
ac 1) When pyspark code is deployed on a running cluster, the cluster is restarted
