### ISSUE TITLE
[ChargePrices] ChargePricesUpdated

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#329]

**Comment by mknic** [comment]
@MadsBloendAndersen the `ChargePricesUpdated` event is not in scope for team volt to implement within the current PI so we can't start the work on this issue in the next coming sprint and I would thereby not put too much energy into refining the issue. 

The "only" event from charges we can implement is [ChargeCreated](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#.ChargeCreated)
