### ISSUE TITLE
[Spike] Result message handling in pyspark

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#347]
Hypothesis: 

- Can we do XML generation of results in pyspark?
- Can we easy do ETL of result dataframes into json (for coordinator) / XML (for internal postoffice interaction)

**Comment by ZavezX** [comment]
Libraries available to work with generating XML files based on data frames:

**spark-xml**
- https://docs.microsoft.com/en-us/azure/databricks/data/data-sources/xml
- https://github.com/databricks/spark-xml

**XStream**
- https://x-stream.github.io/index.html

**Comment by ZavezX** [comment]
Based on findings in above links, it is advised that we stick to handling XML in C# code.

As for saving results in delta lake I have created a new issue for that.
