### ISSUE TITLE
Create RSM-014 CIM/XML message for Grid Company (MDR)

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#348]
**Description:**
We need to create a converter, that transforms the following results from JSON to [RSM-014 CIM XML](https://energinet.sharepoint.com/sites/Joules/Delte%20dokumenter/General/BRS%20og%20RSM%20guides/RSM's/RSM-014-NotifyAggregatedTimeSeries.xml)

Grid company (MDR):

Net exchange per grid area
Production per grid
Hourly consumption per grid
Flex consumption per grid
Total consumption (Hourly production per grid area + net exchange per grid area)

See example of message content here: #483

AC1: Mocked result json files(s) is/are added to a result blob, these are fetched, converted to CIM xml and added to the local post office location.
AC2: The schema of the CIM message is validated.
AC3: The data in the CIM xml is validated by PO and SME

![coordinator to postoffice.drawio.png](https://images.zenhubusercontent.com/60daeef39cad4c6910c63174/8ad05a49-4363-429f-b68c-3a0499a0c25d)

**Comment by johevemi** [comment]
Story'ish suggestions:
- Get integration test working
- Connect blob storage to AggregationResultReceiver
- Coordinator to AggregationResultReceiver with service bus
- Await Titans local post office connection
- Refactor CimXmlConverter. Create object that matches the representation of one cim/xml document. Map ResultData to CimXmlObject and write object to cim/xml document
- Manage const data in CimXmlConverter and collect the data from relevant sources
