### ISSUE TITLE
Create streaming databricks job including CI/CD

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#388]
By introducing a streaming job we need to add CD pipeline to provision the infrastructure.
Get inspiration from Volt who already have a cluster with a streaming job inside implemented in terraform: 

**CI**
https://github.com/Energinet-DataHub/geh-timeseries/blob/main/.github/workflows/streaming-job.yml

**Infrastructure**
https://github.com/Energinet-DataHub/geh-timeseries/tree/main/build/modules/streaming_job
https://github.com/Energinet-DataHub/geh-timeseries/tree/main/build/infrastructure/databricks_streaming_job

AC1: Create streaming cluster
AC2: Create streaming job within the streaming job cluster (AC1)
AC3: Find a proper way to mange streaming job in different environments (dev, test, preprod, prod)

**Note**
Speak to Volt about how they manage start/stop of their streaming job in dev/test environments.

**Comment by MadsBloendAndersen** [comment]
@mknic will refine
