### ISSUE TITLE
Create event listening streaming job (infrastructure)

### ISSUE THREAD

**Issue by kristianschneider** [Energinet-DataHub/geh-aggregations#397]
We need a streaming job that listens to changes in the events delta lake. 
On changes, the event is streamed into the job where it is processed by the Adhoc model creation engine.

![image.png](https://images.zenhubusercontent.com/60dae136fad0561c9902148c/4ef08c01-ded8-444f-8dc1-51ef82fedd6d)

AC1: An event listening streaming job is created via terraform
AC2: The parameters for the events delta lake is provided to the job via terraform parameters
AC3: A python main code file is created and wired up to use the events delta lake parameters
AC4: The python main code uses https://click.palletsprojects.com/en/8.0.x/ as the method to get command line arguments

**Comment by mknic** [comment]
AC1, AC2 and AC3 are solved in #428. In terms of AC4 I don't think it's worthing changing now. 

I read about pros and cons between `ArgParse` and `Click` [here](https://collectiveacuity.medium.com/argparse-vs-click-227f53f023dc) and based on that we should not spent time on changing to `Click` right now.
