### ISSUE TITLE
Update Esett certifikat towards BizTalk

### ISSUE THREAD

**Issue by kristianschneider** [Energinet-DataHub/geh-aggregations#463]
1. Update certificate in PREprod (DevOps library secure files)
2. Deploy to PREprod
3. Request PIM access and verify updated values for certificate and secure key

4. repeat step 1-3 on PROD
5. Notify Integration team when we are ready with the new certificate (Mikael Kristensen)

**Comment by MadsBloendAndersen** [comment]
incident created towards IT client management (#INC0268631) to order new certificate

**Comment by MadsBloendAndersen** [comment]
@kristianschneider du skulle gerne modtage et certifikat snarest.

**Comment by ZavezX** [comment]
Apparently terraform uses byte comparison on base64 encoded string when comparing current vs new state, which results in the new .pfx file containing new certificate wouldn't be recognized as a new change. Terraform would not update appsettings in that case.

I fixed it by creating a dummy .pfx file with much less content and deployed it all the way through to production, then I uploaded the new .pfx file for all envoironments and deployed to all environments once more, which got the changes in based on the new .pfx file with new certificate information.

But even though the certificate is updated we still get exceptions when trying to send through BizTalk.

I will reach out to integration team once again to find a solution.

**Comment by ZavezX** [comment]
Today I had a session with Michael Christensen from integration team regarding differences in base64 string differences from eSett in our end and IIS server in their end.
We came to the conclusion, that we use a .pfx file and that is causing the difference when encoding the content into base64 string.
I uploadet the .cer files instead and made the changes in code to select the new .cer files instead, but the pipeline does not work as it is now because of an error stating that Azure Login failed due to an expired key.
I am in the process of contacting CCOE to figure out how we can solve this as I cannot solve it on my own.

**Comment by ZavezX** [comment]
I have created three incidents with numbers:
-  INC0271187
- INC0271189
- INC0271193

With request to update secrets on Service Principals used in eSett build pipeline.

**Comment by ZavezX** [comment]
I communicated with Mikael Bach Jacobsen from CCoE and on request from his side I created a user story on their board: (here)[https://dev.azure.com/energinet/ENDK/_boards/board/t/CCoE/Stories/?workitem=234683] with a description of what we need from them.

**Comment by ZavezX** [comment]
After deployment started working again and the new certificate got deployed, communication with BizTalk still did not work. I contacted Michael Christensen from Integration Team and got him to verify that the certificate was working in their end, and it seems that it doesnø't work. I am now waiting to hear from him when he has fixed it in their end so we can try again.

**Comment by ZavezX** [comment]
I contacted Michael Christensen to get a status and he said that he was not able to fix the issue with the certificate not working on the BizTalk server. He thinks he might need to aquire a new certificate from Frank Ulrick. He will get back to me when he has done the work in his end. He didn't state a timeline.

**Comment by ZavezX** [comment]
I reached out to Michael Christensen again today and the status is that he has received a new certificate from Ulrik and a password for it on SMS, but he is unable to check if it works until tonight. I will check up on the matter tomorrow morning.

**Comment by ZavezX** [comment]
Today I tested the new certificate in preprod environment and it was successful. I have reached out to Michael Christensen to plan when the certificate security gets turned on in production to be done tuesday december 14. Before that we need to make a deployment to production in our end with the updated certificate and secure string.
