### ISSUE TITLE
Function for JobCompleted servicebus message 

### ISSUE THREAD

**Issue by ZavezX** [Energinet-DataHub/geh-aggregations#483]
### Description

We need a function listening for a ServiceBus message called `JobCompleted` that should fetch relevant data from SQL based on the `JobId` in the message.

The function's task should be to create new ServiceBus message called `ResultReadyForConversion` that should consist of:
```
{
	"JobId": "{Id from job in SQL}",
	"SnapshotId": "{Id from Snapshot in SQL}",
	"ResultId": "{Id from Result in SQL}",
	"JobType": "{JobType enum from SQL}",
	"ProcessType": "{ProcessType from Job in SQL}",
	"ProcessVariant": "{ProcessVariant from Job in SQL}",
	"Resolution": "{Resolution from Job in SQL}",
	"ResultPath": "{Path from JobResult in SQL}",
	"Grouping": "{Grouping from Result in SQL}",
	"FromDate": "{FromDate from Snapshot in SQL}",
	"ToDate": "{ToDate from Snapshot in SQL}"
}
```

The  `ResultReadyForConversion` message should be published to the internal ServiceBus.

`ResultReadyForConversion` message should be consumed in #348

### Acceptance Criteria:

1. Function is created which is triggered by `JobCompleted` ServiceBus message.
2. Function publishes `ResultReadyForConversion` ServiceBus message with data from SQL based on `JobId` from `JobCompleted` message.

**Comment by johevemi** [comment]
Should ResultPath be ResultPaths and contain a list of ResultPath.
Are we missing receiver_MarketParticipant.marketRole.type in the object
