### ISSUE TITLE
Manage const data in CimXmlConverter and collect the data from relevant sources

### ISSUE THREAD

**Issue by johevemi** [Energinet-DataHub/geh-aggregations#514]
Manage const values in the cim/xml converter.
Type: (E31) const
SectorType: (23) electricity
Product: (8716867000030) depends on sectortype
Unit: (KWH) depends on sectorType
Version: number of runs on same period

Sender always Datahub for now
SenderId: (5790001330552)
SenderCodingSchema: (A10)
SenderRole: (DGL)

Get from grid area lookup (MDR)
GridAreaCodingSchema:
RecipientId:
RecipientCodingSchema:
RecipiantRole:

**Comment by johevemi** [comment]
@MadsBloendAndersen

**Comment by MadsBloendAndersen** [comment]
@johevemi the following information need to be present when converting the results to CIM XML: 
![image](https://user-images.githubusercontent.com/72008712/144195100-4c838024-b362-4ba5-89db-be0bf7dd668b.png)
