### ISSUE TITLE
Status on specific messages are not updated 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#515]
Status on the following messages are not updated

Oprettelse Dato	Netområde	Besked ID	Sender	Modtager	Besked type	Status	Start dato	Slut dato	Afsendt fil	Kvittering fil
29-nov-2021 22:40:58	740	310054726-3	5790000705184	44X-00000000004B	(MGXI) Receive MGA Exchange	Sendt	17-nov-2021	18-nov-2021	Link to file	
29-nov-2021 22:40:58	740	310054726-4	5790000705184	44X-00000000004B	(MGXI) Receive MGA Exchange	Sendt	17-nov-2021	18-nov-2021	Link to file	
29-nov-2021 22:37:16	003	310053981	5790002606892	44X-00000000004B	(MEPI) Merged Production	Sendt	17-nov-2021	18-nov-2021	Link to file	
29-nov-2021 22:37:03	003	310053920-21	5790002606892	44X-00000000004B	(MGXI) Receive MGA Exchange	Sendt	17-nov-2021	18-nov-2021	Link to file	

We need to understand why the status is not changed.

**Comment by ZavezX** [comment]
I have checked the logs and it seems that we have not received anything from eSett on the mentioned message ids.
