### ISSUE TITLE
Hourly settled metering point is shown as profiled settled in GUI

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#540]
When I create an hourly settled metering point (settlement method = E02) Then in GUI is says "Skabelon" (Profiled), but is should say "Time afregnet" instead (or in English "Hourly settled")

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/76125d6a-26c4-4a6e-a4c9-d0d52f5db0ea) 

Cope of the XML message I am forwarding through postmand (CreateSingleConsumptionMP)

<?xml version="1.0" encoding="UTF-8"?>

<cim:AccountingPointcharacteristics_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ebix.org:structure:accountingpointcharacteristics:0:1" xsi:schemaLocation="urn:ebix.org:structure:accountingpointcharacteristics:0:1 urn-ediel-org-structure-accountingpointcharacteristics-0-1.xsd">
	<cim:mRID>String</cim:mRID>
	<cim:type>E58</cim:type>
	<cim:process.processType>E02</cim:process.processType>
	<cim:businessSector.type>E24</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="NFI">1234567890123</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="NLT">DHGLN</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2021-06-17T09:30:47Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>{{transactionId}}</cim:mRID>
		<cim:businessProcessReference_MktActivityRecord.mRID>String</cim:businessProcessReference_MktActivityRecord.mRID>
		<cim:originalTransactionIDReference_MktActivityRecord.mRID>String</cim:originalTransactionIDReference_MktActivityRecord.mRID>
		<cim:validityStart_DateAndOrTime.dateTime>2021-09-25T22:00:00Z</cim:validityStart_DateAndOrTime.dateTime>
		<cim:snapshot_DateAndOrTime.dateTime>2001-12-17T09:30:47Z</cim:snapshot_DateAndOrTime.dateTime>
		<cim:MarketEvaluationPoint>
			<cim:mRID codingScheme="NBA">{{gsrn}}</cim:mRID>
			<cim:meteringPointResponsible_MarketParticipant.mRID codingScheme="NDE">a</cim:meteringPointResponsible_MarketParticipant.mRID>
			<cim:type>E17</cim:type>
			<cim:settlementMethod>E02</cim:settlementMethod>
			<cim:meteringMethod>D02</cim:meteringMethod>
			<cim:connectionState>D03</cim:connectionState>
			<cim:readCycle>PT1H</cim:readCycle>
			<cim:netSettlementGroup>6</cim:netSettlementGroup>
            <cim:nextReadingDate>0101</cim:nextReadingDate>
			<cim:meteringGridArea_Domain.mRID codingScheme="NIE">870</cim:meteringGridArea_Domain.mRID>
            <cim:linked_MarketEvaluationPoint.mRID codingScheme="NAZ">575774240560385464</cim:linked_MarketEvaluationPoint.mRID>
			<cim:physicalConnectionCapacity unit="MAW">1000</cim:physicalConnectionCapacity>
            <cim:mPConnectionType>D02</cim:mPConnectionType>
			<cim:disconnectionMethod>D01</cim:disconnectionMethod>
			<cim:asset_MktPSRType.psrType>D12</cim:asset_MktPSRType.psrType>
			<cim:productionObligation>true</cim:productionObligation>
			<cim:Series>
				<cim:product>8716867000030</cim:product>
				<cim:estimatedAnnualVolume_Quantity.quantity>0</cim:estimatedAnnualVolume_Quantity.quantity>
				<cim:quantity_Measure_Unit.name>KWh</cim:quantity_Measure_Unit.name>
			</cim:Series>
			<cim:contractedConnectionCapacity unit="MAW">2000</cim:contractedConnectionCapacity>
			<cim:ratedCurrent unit="AMP">5000</cim:ratedCurrent>
			<cim:energySupplier_MarketParticipant.mRID codingScheme="A02">a</cim:energySupplier_MarketParticipant.mRID>
			<cim:supplyStart_DateAndOrTime.dateTime>2001-12-17T09:30:47Z</cim:supplyStart_DateAndOrTime.dateTime>
			<cim:description>String</cim:description>
			<cim:usagePointLocation.mainAddress>
				<cim:streetDetail>
					<cim:number>123</cim:number>
					<cim:name>Test Street</cim:name>
					<cim:type>String</cim:type>
					<cim:code>1234</cim:code>
					<cim:buildingName>20</cim:buildingName>
					<cim:suiteNumber>21</cim:suiteNumber>
					<cim:floorIdentification>22</cim:floorIdentification>
				</cim:streetDetail>
				<cim:townDetail>
					<cim:code>123</cim:code>
					<cim:section>321</cim:section>
					<cim:name>Test City</cim:name>
					<cim:stateOrProvince>String</cim:stateOrProvince>
					<cim:country>DK</cim:country>
				</cim:townDetail>
				<cim:status>
					<cim:value>555</cim:value>
					<cim:dateTime>2021-09-17T09:30:47Z</cim:dateTime>
					<cim:remark>String</cim:remark>
					<cim:reason>String</cim:reason>
				</cim:status>
				<cim:postalCode>8000</cim:postalCode>
				<cim:poBox>5000</cim:poBox>
				<cim:language>Danish</cim:language>
			</cim:usagePointLocation.mainAddress>
			<cim:usagePointLocation.actualAddressIndicator>true</cim:usagePointLocation.actualAddressIndicator>
			<cim:usagePointLocation.geoInfoReference>8E58B34D-EFE2-43AA-8143-80A7B2B0EF73</cim:usagePointLocation.geoInfoReference>
			<cim:parent_MarketEvaluationPoint.mRID codingScheme="NSI">a</cim:parent_MarketEvaluationPoint.mRID>
			<cim:parent_MarketEvaluationPoint.description>E17</cim:parent_MarketEvaluationPoint.description>
			<cim:Child_MarketEvaluationPoint>
				<cim:mRID codingScheme="NCS">a</cim:mRID>
			</cim:Child_MarketEvaluationPoint>
		</cim:MarketEvaluationPoint>
	</cim:MktActivityRecord>
</cim:AccountingPointcharacteristics_MarketDocument>

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten + @MrDach + @ZavezX + @dzhavat do you know where this issue belongs? Is this a frontend or backend fix?

**Comment by frontend-specialisten** [comment]
@MadsBloendAndersen It could be our translations which is incorrect:
https://github.com/Energinet-DataHub/greenforce-frontend/blob/main/libs/dh/globalization/assets-localization/src/assets/i18n/da.json

Because I can see that "Time afregnet" is configured as E01

**Comment by dzhavat** [comment]
@MadsBloendAndersen Looks like it's an issue with the translation file. The values for "E01" and "E02" should be switched. I will fix that in a minute. 

As for English translations, I have take the values from following file: (Teams) GreenForce -> Filer -> CIM -> Kodelister og Attributter -> Kodeliste DH3 - CIM inkl. att. tilknytning.xlsx. Let me know if I should update the English translations. 

![image](https://user-images.githubusercontent.com/1096332/146371831-cb9f24dd-daaa-4078-a955-9ad3ccfef1e7.png)

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten + @dzhavat yes i can see in the translation file that E01 = Hourly and E02 is profiled, it should be the other way around.
