### ISSUE TITLE
fix nullable properties in genereated ts models

### ISSUE THREAD

**Issue by ZavezX** [Energinet-DataHub/geh-aggregations#545]
There is a prblem with the auto generated typescript models based on the open api json file where null attributes are set on properties even though the property is not null. This only happens on reference objects.

### Acceptance Criteria
- [ ] typescript models are generated without null attribute on non-nullable reference type objects

**Comment by MadsBloendAndersen** [comment]
@ZavezX will this issue solve that properties that are not relevant for a specific metering point is not shown in GUI, when creating that metering point?

**Comment by ZavezX** [comment]
@MadsBloendAndersen No, this issue is about the model that we use in the front-end which is auto generated from the API from Metering Point domain. This issue does not fix anything in the UI.
