### ISSUE TITLE
Error: bundle initial exceeded maximum budget. Budget 1.00 MB was not met by 85.93 kB with a total of 1.08 MB.

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/geh-aggregations#549]
Due to changes of authentication, the initial bundle size is not met by 85.93 kB. This should be looking into and fix correctly. 

Currently the app performance budget has been increased as a temporary fix.

**Acceptance criteria:**
- [ ] Dh app initial bundle size should be <= 1mb

**Comment by mknic** [comment]
Replaced by: https://github.com/Energinet-DataHub/greenforce-frontend/issues/341
