### ISSUE TITLE
Create custom sign-up screen for GUI

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/geh-aggregations#555]
We don't have any design for this screen, so it has been made with inspiration of the login screen.
Links for sign up for all the environments can be found here:
https://github.com/Energinet-DataHub/green-force-art/blob/main/wiki/datahub/environments/signup-and-signin-to-datahub-app.md

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten Is it possible to make a link to the sign up page , on the login page?

**Comment by frontend-specialisten** [comment]
@MadsBloendAndersen I will try look what we can do, but it should be possible

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten i can create a new story for that if you'll like?
