### ISSUE TITLE
Fix unit / integration tests (frontend)

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/geh-aggregations#579]
The backend has now enabled authentication which means our unit / integration tests which integrates with the backend now can't execute. 

For now these tests has been marked as "skipped" you can find which here:
https://github.com/Energinet-DataHub/greenforce-frontend/pull/332/files

libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.spec.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point-search.component.spec.ts
libs/dh/shared/data-access-api/src/lib/metering-point-api-v1.spec.ts

**Technical notes:**
Suggestion will be to use MSW to mock out the backend entirely for our unit & integration tests. However the integration to the backend still provides value but should be considered as E2E or healthchecks instead.

**Comment by mknic** [comment]
Issue moved to [Energinet-DataHub/greenforce-frontend #347](https://github.com/Energinet-DataHub/greenforce-frontend/issues/347) via [**ZenHub**](https://www.zenhub.com/)
