### ISSUE TITLE
[Enabler] Implement pyspark integration test concept

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-aggregations#623]
Synopsis
-----------------
As a developer
I need the foundation for creating pyspark integration tests
So that I can afterward create the tests that are required to achieve the necessary team quality confidence

Acceptance Criteria
-----------------
[ ] An example integration test that developers can execute as part of the test suite on localhost machines test is available

Tasklist
-----------------
- [ ] ~~Create & teardown of Azure EventHub ressource~~ UPDATE: We switched to narrow integration testing thus avoiding the EventHub
- [x] Create integration test of TimeSeriesPersister

Notes from Scenario Container
----------------
![IntegrationTestContainer.drawio.png](https://images.zenhubusercontent.com/60daeef39cad4c6910c63174/30138ed8-4457-4e61-9e0a-66fe819c8344)

**Description:**
- Integration tests as pytest tests in container
- Jobs are executed in container on the spark instance (test setup must start the job)
- Non-mockable resources like Event Hub namespace and blob storage for Delta Lakes are available
	- Same concept as TestCommon where resources are provided by Mighty Ducks
	- Connection strings etc are obtained from the keyvault
	- The keyvault url is the sole configuration needed in order to execute the tests
- Regarding CI no changes should be needed as integration tests are just executed by the same action that already execute the unit tests

**Info**
- [This obsolete integration test](https://github.com/Energinet-DataHub/ARCHIVED-green-energy-hub/blob/main/src/integration-test/streaming-test.py) might provide some inspiration
- Python packages for managing or using Azure resources can be found [here](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-library-package-index)

**Comment by lasrinnil** [comment]
https://github.com/indy-3rdman/docker-dotnet-spark

https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/ubuntu-instructions

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , @lasrinnil , @johevemi 

This story was apparently not updated when we split it at the PI planning. I suggest something like the following:

Title: [Enabler] Implement pyspark integration test concept

**Synopsis**
As a developer
I need the foundation for creating pyspark integration tests
So that I can afterward create the tests that are required to achieve the necessary team quality confidence

**Acceptance Criteria**
[ ] An example integration test that developers can execute as part of the test suite on localhost machines test is available

**Comment by lasrinnil** [comment]
I did Update it. But not good enough though 😅 great writedown, I say let's overwrite the current title and description

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier Sound good 👍
