### ISSUE TITLE
Information i response-header 'MessageType'

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-aggregations#628]
MessageHub har fået et krav om nyt funktionalitet fra aktørerne, som kræver at I angiver ekstra information, når I sender data over til os (i DataAvailable).

Casen er, at aktører vil gerne kende indholdet af beskeden de peek'er, uden at åbne og parse selve svaret.

MessageHub har fået en ny response-header 'MessageType' på alle Peek-svar. Indtil videre er der aftalt, at feltet skal indeholde CIM-typen på dokumentet. For eksempel, <cim:NotifyPriceList_MarketDocument... skal svares i headeren som 'MessageType': 'NotifyPriceList'.

Energinet.DataHub.MessageHub.Client (version 1.9.1 fra 31. januar) har et nyt felt i DataAvailableNotificationDto, hvor I kan angive dokumenttypen. Vi sender denne text uændret videre i headeren, når dokumentet bliver peek'et.

**Acceptance criteria:** 
- [ ] Data available notifications is enriched with MessageType
- [ ] Notify TML when the correction has been done. Then Titans will enable the functionality again (currently disabled)

**Comment by MadsBloendAndersen** [comment]
Information fra titans angående message handling

**Comment by lasrinnil** [comment]
Implementing MessageType in header is moved to this issue: https://app.zenhub.com/workspaces/joules-pi-planning-61ae6312e024cc00167f35aa/issues/energinet-datahub/geh-aggregations/630
