### ISSUE TITLE
616 enabler: We can't create metering points in t-001

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-aggregations#726]
**Synopsis**
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/24a0741f-216f-47ac-b23e-ec3530c38e09)

**Acceptance-Criteria**
- [ ] AC1: Members of team Joules can create metering points in t-001 using the designated test actor (GLN 8100000000204)

**Comment by PerTHenriksen** [comment]
Vi afventer en synkronisering fra Batman, hvorefter vi bør kunne teste oprettelsen:

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/1faac833-f7af-4e26-817b-5cc6ac9519ae)
