### ISSUE TITLE
1) Request balance fixing for 1st of June 2022 for wholesale test grids

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-aggregations#746]
## Problem Description
As a user
I want a graphical user interface
So that I can request a balance fixing for 1st of June 2022 per grid area. 

Business note: We'll work with Titans to get wholesale test grid areas 805 and 806. This has been agreed with Rasmus.

## Scope
The scope is solely to provide a user interface for users but no actual process will be started.
Currently, the functionality will not be limited to FAS users as user roles and rights will not be available in the foreseeable future.
Locking of the period is not including in this feature.

## Acceptance criteria and must have scope

- [x] AC1: The menu and page are accessible to users.

**Comment by PerTHenriksen** [comment]
https://miro.com/app/board/uXjVODthRHw=/?invite_link_id=155930882924
