### ISSUE TITLE
2) Peek/dequeue a RSM-014 without a result section for GridAccessProviders

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-aggregations#748]
## Problem Description
As a GridAccessProvider
I want to peek/dequeue an empty RSM-014 CIM XML
So that I can verify that I can receive aggregation output

## Scope
It is accepted that the RSM-14 message might not be able to be schema parsed when this feature is done.
A schema valid RSM-14 will be delivered in #749

## Acceptance criteria and must have scope
- [ ] The GridAccessProvider can Peek/deque an RSM-014 CIM XML, which does, however,  not contain the section with the aggregation result.

**Comment by BjarkeMeier** [comment]
@PerTHenriksen, should we add an AC about not releasing this functionality in (pre)production environments?
And create a corresponding story?
