### ISSUE TITLE
As a user I want to navigate to the start process page

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-aggregations#762]
Synopsis
----------------
As a user
I want to navigate to the start process page
So that I can verify that I have access to the page

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/1764fae1-8553-4ac1-9bd7-9ac1817e79b2)

Acceptance-Criteria
----------------
- [ ] AC1: Users can access the start process page

Tech-Notes
----------------

Tasks
-----------------
- [ ]

**Comment by BjarkeMeier** [comment]
Test: According to @johevemi the page under menu item "Settlements" is the "start proces" page. I can navigate to this (empty) page in t-001. Thus I conclude the story is ok.
