### ISSUE TITLE
As a user I want to start an aggregation process

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-aggregations#763]
Synopsis
----------------
As a user
I want to start an aggregation process for yesterday on the aggregation test grid areas
So that I acquire the functionality to start the aggregation process

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/ce6a555e-aad1-4165-9868-c3d6a8c12d40)

Acceptance-Criteria
----------------
- [ ] AC1: A user can start an aggregation process for yesterday for the aggregation test grid areas (most likely by the click of a button)

Tech-Notes
----------------

Tasks
-----------------
- [ ]

**Comment by BjarkeMeier** [comment]
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/e5d3037a-2d5b-4c0d-938b-16c7925891b9)

Danish:
- Lowercase P in header
- A dot in the end of the sentence?
- "proces" (not process)
- "i går" (not igår)
- Will it be 802 and 803 in every environment? (also applies to english)

English:
- A dot at the end of the sentence?

**Comment by BjarkeMeier** [comment]
Testet ok.
