### ISSUE TITLE
As a user I want to navigate to the process overview page

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-aggregations#764]
Synopsis
----------------
As a user
I want to navigate to the control report page
So that I'm able to find the page which will eventually supply me with the control report

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/fe0f30f3-cea2-480e-9135-e577c5b70ae7)

Acceptance-Criteria
----------------
- [ ] AC1: Users can access the control report page

Tech-Notes
----------------

Tasks
-----------------
- [ ]

**Comment by johevemi** [comment]
Note: Two separate menu points have been created instead of one menu point with two child points, this is because the child menu point functionality has not been developed yet
