### ISSUE TITLE
Update repo documentation

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-aggregations#775]
Synopsis
----------------
As a team member
I want to update the repo documentation
So that the documentation is up2date and useful (to whom?)

Acceptance-Criteria
----------------
- [x] AC1: All documentation reflects the current state of the repo
- [x] AC2: All invalid, incorrect, or out-of-date documentation has been removed
- [x] AC3: The open-source documentation meets the requirements of the business

Tech-Notes
----------------

Tasks
-----------------
- [ ]

**Comment by BjarkeMeier** [comment]
Blocked as we need secrets in the repo that will be set up by team Mighty Ducks.
@mknic has agreed to have the team configure the new wholesale repo.

**Comment by ZavezX** [comment]
All documentation seems to be there.
