### ISSUE TITLE
Document wholesale domain design and architecture

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-aggregations#780]
Value proposition:
- Optimize the use of the external consultant
- Optimize knowledge sharing from @ZavezX 
- Risk mitigate
- Provide early input to architects
- Provide an architectural runway for the domain

AC:
- [ ] The team agree on the architecture of wholesale domain and has created a sufficient diagram to support it

**Comment by lasrinnil** [comment]
Test
-----
I have verified that I personally feel confident with the current documentation of design and architecture written in the wholesale domain

**Comment by BjarkeMeier** [comment]
Closed as per [this team talk](https://teams.microsoft.com/l/message/19:9be4db802bd24ed99af96f025a839eb2@thread.tacv2/1654254350044?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e986ad70-5310-4581-bc33-eed0503bdfde&parentMessageId=1654254350044&teamName=Joules&channelName=General&createdTime=1654254350044).
